Fix typos and grammatical errors across multiple documentation files
ourzora/zora-protocol pull request #470
Opened 2024-12-06 16:09 UTC by Dimitrolito

This pull request fixes several typographical and grammatical issues across various documentation files in the project. Changes include the correction of articles ("a" vs. "an") and clarification of phrases for improved readability and accuracy.

#### Motivation and Context:
These changes were made to address typos and ensure consistency in grammar, which helps improve the clarity and professionalism of the documentation. Some issues included the incorrect use of articles and repetitive phrases, which could confuse readers.

#### Changes:
- Fixed the use of "a" vs. "an" where appropriate (e.g., "a Uniswap V3 Pool" → "an Uniswap V3 Pool").
- Removed repetitive phrases (e.g., "when users when users" → "when users").
- Corrected other minor typographical errors for clarity.

#### Impact:
These changes are purely grammatical and will not affect the functionality of the codebase. They help improve the documentation and ensure consistency throughout.

#### Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I added a changeset to account for this change.

#### Reviewer Checklist:
- [x] My review includes a synopsis of the changes and potential issues.
- [x] The code style is enforced.
- [x] There are no risky or concerning changes in the PR.

2025-01-07 14:00 UTC, oveddan requested changes
thanks for catching and fixing all these.  please undo the changes where instructed and then LGTM

2025-01-07 14:00 UTC, oveddan commented on docs/pages/bug-bounty/bug-bounty-program.mdx
> -To submit your report, send an email to [security@zora.co](mailto:security@zora.co) and include the following details:
this isn't a correct grammar fix - the original text was fine

2025-01-07 14:00 UTC, oveddan commented on docs/pages/bug-bounty/bug-bounty-program.mdx
> -- When duplicates occur, we will only accept the first report that was received, as long as it fulfils our submission criteria and can be fully reproduced.
good fix

2025-01-07 14:00 UTC, oveddan commented on docs/pages/changelogs/1155-contracts.mdx
> -- [d460e79c](https://github.com/ourzora/zora-protocol/commit/d460e79c): - Introduced a `reduceSupply` function allowing an approved minter or admin to reduce the supply for a given token id. New supp
good fix thank you

2025-01-07 14:00 UTC, oveddan commented on docs/pages/changelogs/1155-contracts.mdx
> +  Executing premint against contracts not created via premint can be done by passing a `premintCollection` argument to the new `premint` function:
thank you for catching this

2025-01-07 14:00 UTC, oveddan commented on docs/pages/changelogs/1155-contracts.mdx
> +### ZoraCreator1155Impl rewards splits are percentage-based instead of a fixed value.
nice catch

2025-01-07 14:00 UTC, oveddan commented on docs/pages/changelogs/1155-contracts.mdx
> +- 52b16aa: Publishing package in a format that supports commonjs imports by specifying exports.
👌

2025-01-07 14:00 UTC, oveddan commented on docs/pages/changelogs/1155-contracts.mdx
> +- e990b9d: Remove platform referral from RewardsSplits. Use a new signature for 1155 for `mint` which takes an array of reward recipients.
👌

2025-01-07 14:00 UTC, oveddan commented on docs/pages/changelogs/1155-contracts.mdx
> +- 7e00197: \* For premintV1 and V2 - mintReferrer has been changed to an array `mintRewardsRecipients` - which the first element in an array is `mintReferral`, and the second element is `platformRefe
👌

2025-01-07 14:00 UTC, oveddan commented on docs/pages/changelogs/1155-contracts.mdx
> +  - new function `premintV1` - takes a `PremintConfig`, and premint v1 signature, and executes a premint, with the added functionality of being able to specify mint referral and mint recipient
👌

2025-01-07 14:00 UTC, oveddan commented on packages/protocol-sdk/src/sparks/sparks-contracts.ts
> + * @param tokenIds - The mint token ids to use
👌

2025-01-07 14:00 UTC, oveddan commented on packages/erc20z/README.md
> +Upon calling setSale() a sale will be created for the 1155 NFT provided. In this function, it will also create an ERC20z token and an Uniswap V3 Pool. The ERC20z token will be used as a pool pair (WE
this isn't correct - we use "an" before words that begin with a vowel sound, and "a" before words that begin with a consonant sound.
Even though "Uniswap" starts with the letter 'U', it's pronounced with a 'you' sound (like "YOU-niswap"), which is a consonant sound. Therefore, we use "a" instead of "an".

2025-01-07 14:00 UTC, oveddan commented on docs/snippets/protocol-sdk/create/withdrawRewards.ts
> +  // but the rewards will always be pulled to the account that holds the balance
thank you

2025-01-07 14:00 UTC, oveddan commented on docs/pages/zora-network/network.mdx
> +Zora Sepolia Network is a Testnet L2 built on top of Ethereum Sepolia using the [OP stack](https://stack.optimism.io/).
good catch

2025-01-07 14:00 UTC, oveddan commented on docs/pages/protocol-sdk/creator/premint.mdx
> +original creator of the Premint. The account that brings the Premint onchain will earn the first minter reward.
thank you

2025-01-07 14:00 UTC, oveddan commented on docs/pages/protocol-sdk/creator/onchain.mdx
> +A price per token can be optionally set to earn additional ETH on the primary sale when each token is minted, by setting `token.salesConfig.pricePerToken`.
👍

2025-01-07 14:00 UTC, oveddan commented on docs/pages/protocol-sdk/collect/getTokensOfContract.mdx
> +**Both onchain** and **premint (gaslessly created)** tokens of a Zora 1155 contract can be retrieved using the Collector Client function
👍

2025-01-07 14:00 UTC, oveddan commented on docs/pages/contracts/ZoraTimedSaleStrategy.mdx
> +- Each owned ERC1155 should be backed and unwrappable by 1 ERC20, and vice versa.
👍

2025-01-07 14:00 UTC, oveddan commented on docs/pages/contracts/ZoraTimedSaleStrategy.mdx
> +To mint an 1155 token, the `mint` function is called on the ZoraTimedSaleStrategy contract with the mint fee of 0.000111 eth x quantity to mint sent with the call. In the `mint` call, 0.0000111 eth x
nice fix

2025-01-07 14:00 UTC, oveddan commented on docs/pages/contracts/ZoraTimedSaleStrategy.mdx
> +Upon calling `setSale()` a sale will be created for the Zora 1155 NFT along with creating an ERC20z token and an Uniswap V3 Pool.
it should still be `a` - see the comment below

2025-03-13 02:56 UTC, iainnash commented
These are too difficult to organize with merge conflicts and no actual code changes so I'm going to close this out.

2025-03-13 02:56 UTC, closed without merging